spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
  h2:
    console-enabled: true
springdoc:
  swagger-ui-enabled: true
  swagger-ui.path: /swagger-ui.html
  show-actuator: true
  api-docs-enabled: true